spring:
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://auth-service

logging:
  level:
    root: WARN

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
